// Generated from harness\flows\*.json (the flows the test harness verifies on the whole corpus).
// Regenerate after changing those: the "Harness" block is dropped, names/folders are the Workbench's own.

internal static class BuiltinFlows
{
    public static readonly string[][] All = new string[][]
    {
        new[] { "Format", "Round-trip (parse + emit)", "Parse and re-emit unchanged: shows what the engine understands; includes inlined", @"{""Meta"":{""Name"":""Round-trip (parse + emit)"",""Description"":""Parse and re-emit unchanged: shows what the engine understands; includes inlined"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[]}" },
        new[] { "Format", "Beautify", "Consistent indentation and spacing", @"{""Meta"":{""Name"":""Beautify"",""Description"":""Consistent indentation and spacing"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Beautify"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.BeautifyConfig"",""ConfigJson"":""{\""UseTabs\"":false,\""IndentSize\"":4,\""EmitBlankLines\"":true,\""FunctionSpacing\"":1,\""EmitComments\"":true}""}]}" },
        new[] { "Format", "Beautify (compact)", "Tabs, no comments, no blank lines", @"{""Meta"":{""Name"":""Beautify (compact)"",""Description"":""Tabs, no comments, no blank lines"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Beautify"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.BeautifyConfig"",""ConfigJson"":""{\""UseTabs\"":true,\""IndentSize\"":1,\""EmitBlankLines\"":false,\""FunctionSpacing\"":0,\""EmitComments\"":false}""}]}" },
        new[] { "Format", "Auto-fix", "Fix common mistakes", @"{""Meta"":{""Name"":""Auto-fix"",""Description"":""Fix common mistakes"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Auto-Fixes"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.AutoFixConfig"",""ConfigJson"":""{}""}]}" },
        new[] { "Optimise", "Optimise", "Fold constants, prune dead branches, dedupe directives", @"{""Meta"":{""Name"":""Optimise"",""Description"":""Fold constants, prune dead branches, dedupe directives"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Optimise"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.OptimiseConfig"",""ConfigJson"":""{}""}]}" },
        new[] { "Optimise", "Optimise (everything)", "All optimisations, strip comments", @"{""Meta"":{""Name"":""Optimise (everything)"",""Description"":""All optimisations, strip comments"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Optimise"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.OptimiseConfig"",""ConfigJson"":""{\""RemoveDuplicateDirectives\"":true,\""ConvertIfToSwitch\"":true,\""FoldMathConstants\"":true,\""FoldLogicalConstants\"":true,\""PruneDeadBranches\"":true,\""FoldStringConcats\"":true,\""FoldConsecutiveStringAssigns\"":true,\""BuildStateOptimize\"":2,\""StripComments\"":true,\""PatchIncludeSelfExecution\"":true}""}]}" },
        new[] { "Optimise", "Tree-shake (safe)", "Remove unused library code, conservatively", @"{""Meta"":{""Name"":""Tree-shake (safe)"",""Description"":""Remove unused library code, conservatively"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Tree-shake"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.TreeShakerConfig"",""ConfigJson"":""{\""Profile\"":1}""}]}" },
        new[] { "Optimise", "Tree-shake (aggressive)", "Remove everything unreachable from the entry points", @"{""Meta"":{""Name"":""Tree-shake (aggressive)"",""Description"":""Remove everything unreachable from the entry points"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Tree-shake"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.TreeShakerConfig"",""ConfigJson"":""{\""Profile\"":2}""}]}" },
        new[] { "Minify", "Minify (safe)", "Compact output, local renames; works for every script", @"{""Meta"":{""Name"":""Minify (safe)"",""Description"":""Compact output, local renames; works for every script"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Minify"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.MinifyConfig"",""ConfigJson"":""{\""Level\"":0,\""ExcludeProperties\"":\""\""}""}]}" },
        new[] { "Minify", "Minify (aggressive)", "Renames functions, classes and globals too", @"{""Meta"":{""Name"":""Minify (aggressive)"",""Description"":""Renames functions, classes and globals too"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Minify"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.MinifyConfig"",""ConfigJson"":""{\""Level\"":1,\""ExcludeProperties\"":\""\""}""}]}" },
        new[] { "Minify", "Minify (extreme)", "Also properties and methods; not every script survives", @"{""Meta"":{""Name"":""Minify (extreme)"",""Description"":""Also properties and methods; not every script survives"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Minify"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.MinifyConfig"",""ConfigJson"":""{\""Level\"":2,\""ExcludeProperties\"":\""\""}""}]}" },
        new[] { "Analyse", "Static analysis report", "Unused symbols, argument counts, suspicious code", @"{""Meta"":{""Name"":""Static analysis report"",""Description"":""Unused symbols, argument counts, suspicious code"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Eval Analysis"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.EvalAnalysisConfig"",""ConfigJson"":""{\""ExportType\"":0,\""LaunchBrowser\"":false,\""CacheIncludes\"":true,\""EnableWatchers\"":false}""}]}" },
        new[] { "Analyse", "Logic flow diagram", "Interactive HTML diagram of the code", @"{""Meta"":{""Name"":""Logic flow diagram"",""Description"":""Interactive HTML diagram of the code"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Logic Flow Diagram"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.NodeDiagramConfig"",""ConfigJson"":""{\""IncludeBranches\"":true,\""IncludeLibraryDetails\"":true,\""CollapseIncludes\"":true,\""LaunchBrowser\"":false,\""OutputPath\"":\""${OutputDir}\\\\flow_diagram.html\""}""}]}" },
        new[] { "Instrument", "Trace (functions)", "Log calls of functions, methods and events", @"{""Meta"":{""Name"":""Trace (functions)"",""Description"":""Log calls of functions, methods and events"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Trace Wrapper"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.TraceWrapperConfig"",""ConfigJson"":""{\""TraceFilePath\"":\""${OutputDir}\\\\__trace_dump.json\""}""}]}" },
        new[] { "Instrument", "Trace (lines + profiling)", "Log every line with timing", @"{""Meta"":{""Name"":""Trace (lines + profiling)"",""Description"":""Log every line with timing"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Trace Wrapper"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.TraceWrapperConfig"",""ConfigJson"":""{\""TraceLines\"":true,\""WrapTryCatch\"":true,\""ProfileSpeed\"":true,\""TraceFilePath\"":\""${OutputDir}\\\\__trace_dump.json\""}""}]}" },
        new[] { "Transpile", "Nim transpiler", "AutoHotkey to Nim source (experimental)", @"{""Meta"":{""Name"":""Nim transpiler"",""Description"":""AutoHotkey to Nim source (experimental)"",""EmitDiagnosticsComments"":false,""CustomProperties"":""""},""Steps"":[{""Title"":""Nim Transpiler"",""Icon"":"""",""ConfigType"":""AHK2AST.Plugins.NimTranspilerConfig"",""ConfigJson"":""{\""AddImports\"":true,\""OutputPath\"":\""\"",\""IncludeDebugging\"":true}""}]}" },
    };
}
