using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace AstHarness
{
    /// <summary>
    /// `builtins --docs <AutoHotkeyDocs\docs>`: regenerates src\ast\AhkBuiltins.cs (built-in functions with their
    /// argument counts, built-in variables, built-in classes with their base class) from the AutoHotkey v2 help files:
    /// the index (static\source\data_index.js) says what exists, each function's lib\*.htm syntax block how it is called
    /// (`<span class="optional">` = optional parameters, `...` = variadic), ObjList.htm the class hierarchy.
    /// </summary>
    public static class Builtins
    {
        // Syntax blocks that do not show the variadic tail (checked against the pages' parameter descriptions).
        static readonly Dictionary<string, int[]> Overrides = new Dictionary<string, int[]>(StringComparer.OrdinalIgnoreCase)
        {
            { "DllCall", new[] { 1, int.MaxValue } },  // Type1, Arg1, Type2, Arg2, … "ReturnType"
            { "ComCall", new[] { 2, int.MaxValue } },  // Index, ComObj, Type1, Arg1, …
            // documented on shared pages without a syntax line of their own
            { "ObjPtr", new[] { 1, 1 } }, { "ObjPtrAddRef", new[] { 1, 1 } },        // Objects.htm#ObjPtr
            { "ObjFromPtr", new[] { 1, 1 } }, { "ObjFromPtrAddRef", new[] { 1, 1 } },
            { "ObjHasOwnProp", new[] { 2, 2 } }, { "ObjOwnProps", new[] { 1, 1 } }, // Obj.HasOwnProp(Name) / Obj.OwnProps()
            { "OSError", new[] { 0, 3 } },                                            // OSError(Code?, What?, Extra?)
            { "Class", new[] { 0, int.MaxValue } },                                   // ClassObj(Params*)
            { "Map", new[] { 0, int.MaxValue } },                                     // `Map(Key1, Value1, …)` reads as 4+, but Map() is fine
            { "IsSet", new[] { 1, 1 } },                                              // indexed as an operator (type 4)
        };

        public static int Run(Args a)
        {
            string docs = a.Get("docs", null);
            if (docs == null || !File.Exists(Path.Combine(docs, @"static\source\data_index.js")))
            {
                Console.WriteLine("usage: builtins --docs <folder containing static\\source\\data_index.js> [--out file]");
                return 2;
            }
            string outPath = a.Get("out", Path.Combine(Paths.Repo, @"src\ast\AhkBuiltins.cs"));
            string index = File.ReadAllText(Path.Combine(docs, @"static\source\data_index.js"));
            var entries = Regex.Matches(index, @"\[""((?:[^""\\]|\\.)*)"",""([^""]*)"",(\d)").Cast<Match>()
                .Select(m => new { Name = m.Groups[1].Value, Page = m.Groups[2].Value, Type = int.Parse(m.Groups[3].Value) }).ToList();

            var vars = entries.Where(e => e.Type == 1 && Regex.IsMatch(e.Name, @"^\w+$")).Select(e => e.Name).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(n => n, StringComparer.OrdinalIgnoreCase).ToList();
            var classes = ClassTree(File.ReadAllText(Path.Combine(docs, "ObjList.htm")));
            foreach (var e in entries.Where(e => e.Type == 6 && Regex.IsMatch(e.Name, @"^\w+$")))
                if (!classes.ContainsKey(e.Name)) classes[e.Name] = null;

            var funcs = new SortedDictionary<string, int[]>(StringComparer.OrdinalIgnoreCase);
            var missing = new List<string>();
            foreach (var e in entries.Where(e => e.Type == 2 && Regex.IsMatch(e.Name, @"^\w+$")))
            {
                if (funcs.ContainsKey(e.Name)) continue;
                int[] mm;
                if (Overrides.TryGetValue(e.Name, out mm)) { funcs[e.Name] = mm; continue; }
                string page = Path.Combine(docs, e.Page.Split('#')[0].Replace('/', '\\'));
                string html = File.Exists(page) ? File.ReadAllText(page) : null;
                mm = html != null ? Signature(html, e.Name) : null;
                // lib\Is.htm documents all type checks as one `IsSomething(Value [, Mode])`
                if (mm == null && html != null && e.Page.StartsWith("lib/Is.htm", StringComparison.OrdinalIgnoreCase)) mm = Signature(html, "IsSomething");
                if (mm == null) { missing.Add(e.Name + " (" + e.Page + ")"); mm = new[] { 0, int.MaxValue }; }
                funcs[e.Name] = mm;
            }

            foreach (var kv in Overrides) if (!funcs.ContainsKey(kv.Key)) funcs[kv.Key] = kv.Value; // IsSet is not indexed as a function

            string version = "";
            var vm = Regex.Match(File.ReadAllText(Path.Combine(docs, "ChangeLog.htm")), @"<h2[^>]*>([^<]+)");
            if (vm.Success) version = vm.Groups[1].Value.Trim();

            var sb = new StringBuilder();
            sb.Append("// GENERATED by `harness.ps1 builtins --docs <AutoHotkey docs>` from the AutoHotkey v2 help (").Append(version).Append(").\r\n");
            sb.Append("// Do not edit by hand: regenerate. Functions: minimum/maximum argument count (int.MaxValue = variadic) from each\r\n");
            sb.Append("// page's syntax block; variables: every built-in variable in the index; classes: ObjList.htm, with their base class.\r\n\r\n");
            sb.Append("using System;\r\nusing System.Collections.Generic;\r\n\r\n");
            sb.Append("/// <summary>What AutoHotkey v2 defines itself: the one table every plugin uses for built-in names.</summary>\r\n");
            sb.Append("public static class AhkBuiltins\r\n{\r\n");
            sb.Append("    public const string DocsVersion = \"").Append(version).Append("\";\r\n\r\n");
            sb.Append("    /// <summary>Built-in functions → { min, max } argument count (max int.MaxValue: variadic).</summary>\r\n");
            sb.Append("    public static readonly Dictionary<string, int[]> Functions = new Dictionary<string, int[]>(StringComparer.OrdinalIgnoreCase)\r\n    {\r\n");
            foreach (var kv in funcs)
                sb.Append("        { \"").Append(kv.Key).Append("\", new[] { ").Append(kv.Value[0]).Append(", ").Append(kv.Value[1] == int.MaxValue ? "int.MaxValue" : kv.Value[1].ToString(CultureInfo.InvariantCulture)).Append(" } },\r\n");
            sb.Append("    };\r\n\r\n");
            sb.Append("    /// <summary>Built-in variables (A_…, True, False, …).</summary>\r\n");
            sb.Append("    public static readonly HashSet<string> Variables = new HashSet<string>(StringComparer.OrdinalIgnoreCase)\r\n    {\r\n");
            foreach (var chunk in Chunks(vars, 6)) sb.Append("        ").Append(string.Join(", ", chunk.Select(v => "\"" + v + "\""))).Append(",\r\n");
            sb.Append("    };\r\n\r\n");
            sb.Append("    /// <summary>Built-in classes → base class (null for Any). Nested ones (Gui.Button) by their full name.</summary>\r\n");
            sb.Append("    public static readonly Dictionary<string, string> Classes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)\r\n    {\r\n");
            foreach (var kv in classes.OrderBy(k => k.Key, StringComparer.OrdinalIgnoreCase))
                sb.Append("        { \"").Append(kv.Key).Append("\", ").Append(kv.Value == null ? "null" : "\"" + kv.Value + "\"").Append(" },\r\n");
            sb.Append("    };\r\n\r\n");
            sb.Append(@"    public static bool IsFunction(string name) { return name != null && Functions.ContainsKey(name); }
    public static bool IsVariable(string name) { return name != null && Variables.Contains(name); }
    public static bool IsClass(string name) { return name != null && Classes.ContainsKey(name); }

    /// <summary>A name AutoHotkey defines globally (function, variable or class).</summary>
    public static bool IsBuiltin(string name) { return IsFunction(name) || IsVariable(name) || IsClass(name); }

    /// <summary>The argument count a built-in function accepts.</summary>
    public static bool TryGetArgCount(string name, out int min, out int max)
    {
        int[] mm;
        if (name != null && Functions.TryGetValue(name, out mm)) { min = mm[0]; max = mm[1]; return true; }
        min = 0; max = int.MaxValue;
        return false;
    }

    /// <summary>Every built-in name (for tables that only need the set).</summary>
    public static IEnumerable<string> AllNames()
    {
        foreach (var f in Functions.Keys) yield return f;
        foreach (var v in Variables) yield return v;
        foreach (var c in Classes.Keys) if (c.IndexOf('.') < 0) yield return c;
    }
}
");
            File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
            Console.WriteLine("wrote " + outPath + ": " + funcs.Count + " functions, " + vars.Count + " variables, " + classes.Count + " classes (docs " + version + ")");
            if (missing.Count > 0) Console.WriteLine("no syntax found (any argument count accepted): " + string.Join(", ", missing));
            return 0;
        }

        static IEnumerable<List<string>> Chunks(List<string> items, int n)
        {
            for (int i = 0; i < items.Count; i += n) yield return items.Skip(i).Take(n).ToList();
        }

        /// <summary>{ min, max } over every syntax line of the page that calls <paramref name="name"/> (not as a method).</summary>
        static int[] Signature(string html, string name)
        {
            int min = int.MaxValue, max = -1;
            foreach (Match pre in Regex.Matches(html, @"<pre class=""Syntax""[^>]*>([\s\S]*?)</pre>"))
            {
                foreach (string rawLine in pre.Groups[1].Value.Split('\n'))
                {
                    string line = Markup(rawLine);
                    foreach (Match m in Regex.Matches(line, @"(?<![\w.])" + Regex.Escape(name) + @"(?![\w])(\(|[ \t]+|$)", RegexOptions.IgnoreCase))
                    {
                    string args;
                    if (m.Groups[1].Value == "(")
                    {
                        int depth = 1, i = m.Index + m.Length;
                        int start = i;
                        for (; i < line.Length && depth > 0; i++)
                        {
                            if (line[i] == '(') depth++;
                            else if (line[i] == ')') depth--;
                        }
                        args = line.Substring(start, Math.Max(0, i - 1 - start));
                    }
                    else
                    {
                        // command syntax `Name Arg, Arg`; `Name :=` / `Name.Prop` are not calls
                        string rest = line.Substring(m.Index + m.Length);
                        if (rest.TrimStart().StartsWith(":=") || rest.TrimStart().StartsWith(".")) continue;
                        args = rest;
                    }
                    int lo, hi;
                    Count(args, out lo, out hi);
                    min = Math.Min(min, lo);
                    max = Math.Max(max, hi);
                    break; // one call per line (`HasProp := HasProp(Value, Name)`: the output variable is skipped above)
                    }
                }
            }
            return max < 0 ? null : new[] { min, max };
        }

        /// <summary>Tags removed, optional spans as [ ], entities decoded.</summary>
        static string Markup(string html)
        {
            var sb = new StringBuilder();
            var spans = new Stack<bool>();
            int i = 0;
            while (i < html.Length)
            {
                if (html[i] == '<')
                {
                    int close = html.IndexOf('>', i);
                    if (close < 0) break;
                    string tag = html.Substring(i, close - i + 1);
                    if (tag.StartsWith("<span", StringComparison.OrdinalIgnoreCase))
                    {
                        bool opt = tag.IndexOf("optional", StringComparison.OrdinalIgnoreCase) >= 0;
                        spans.Push(opt);
                        if (opt) sb.Append('[');
                    }
                    else if (tag.StartsWith("</span", StringComparison.OrdinalIgnoreCase))
                    {
                        if (spans.Count > 0 && spans.Pop()) sb.Append(']');
                    }
                    i = close + 1;
                    continue;
                }
                sb.Append(html[i]);
                i++;
            }
            return sb.ToString().Replace("&amp;", "&").Replace("&lt;", "<").Replace("&gt;", ">").Replace("&quot;", "\"").Replace("&nbsp;", " ");
        }

        /// <summary>Parameters of `a, b [, c, d]`: required ones outside [ ], `...` = variadic.</summary>
        static void Count(string args, out int min, out int max)
        {
            min = 0; max = 0;
            bool variadic = false;
            int depth = 0;
            bool inQuote = false;
            var cur = new StringBuilder();
            bool curOptional = false;
            Action flush = null;
            int lo = 0, hi = 0;
            flush = () =>
            {
                string p = cur.ToString().Trim();
                string bare = p.Trim('[', ']', ' ', '\t');
                // `...` / `Params*` / the docs' `Params` (ObjBindMethod(Obj, Method, Params)) = any number
                if (p.Contains("...") || p.Contains("…") || bare.EndsWith("*") || bare == "Params") variadic = true;
                else if (p.Trim('[', ']', ' ').Length > 0) { hi++; if (!curOptional) lo = hi; }
                cur.Clear();
                curOptional = depth > 0;
            };
            curOptional = false;
            foreach (char c in args)
            {
                if (c == '"') inQuote = !inQuote;
                if (!inQuote && c == '[') { depth++; if (cur.ToString().Trim().Length == 0) curOptional = true; continue; }
                if (!inQuote && c == ']') { depth = Math.Max(0, depth - 1); continue; }
                if (!inQuote && c == ',') { flush(); continue; }
                cur.Append(c);
            }
            flush();
            min = lo;
            max = variadic ? int.MaxValue : hi;
        }

        /// <summary>ObjList.htm's nested lists → class name → its base.</summary>
        static Dictionary<string, string> ClassTree(string html)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            int at = html.IndexOf("<li><a href=\"lib/Any.htm\">", StringComparison.Ordinal);
            if (at < 0) return result;
            var parents = new Stack<string>();
            string last = null;
            int depth = 0;
            foreach (Match m in Regex.Matches(html.Substring(at), @"<(/?)(ul|li)[^>]*>|([^<]+)|<a [^>]*>([^<]*)</a>|<[^>]+>"))
            {
                if (m.Groups[2].Success)
                {
                    bool closing = m.Groups[1].Value == "/";
                    if (m.Groups[2].Value == "ul")
                    {
                        if (!closing) { parents.Push(last); depth++; }
                        else { if (parents.Count > 0) parents.Pop(); depth--; if (depth < 0) break; }
                    }
                    continue;
                }
                string text = m.Groups[4].Success ? m.Groups[4].Value : m.Groups[3].Success ? m.Groups[3].Value : null;
                if (text == null) continue;
                text = text.Trim();
                if (!Regex.IsMatch(text, @"^[A-Za-z_][\w.]*$")) continue;
                if (!result.ContainsKey(text)) result[text] = parents.Count > 0 ? parents.Peek() : null;
                last = text;
            }
            return result;
        }
    }
}
